post_install(){
  install-catalog --add /etc/sgml/dsssl-docbook-stylesheets.cat \
      /usr/share/sgml/docbook/dsssl-stylesheets-1.79/catalog

  install-catalog --add /etc/sgml/dsssl-docbook-stylesheets.cat \
      /usr/share/sgml/docbook/dsssl-stylesheets-1.79/common/catalog

  install-catalog --add /etc/sgml/sgml-docbook.cat              \
      /etc/sgml/dsssl-docbook-stylesheets.cat
}

post_upgrade(){
  post_install
}

