post_install(){
  if [ "$(getent group dhcpcd | cut -d ":" -f 3)" != "52" ]; then
    groupadd -g 52 dhcpcd
  fi 
  if [ "$(getent passwd dhcpcd | cut -d ":" -f 3)" != "52" ]; then
    useradd  -c 'dhcpcd PrivSep' \
             -d /var/lib/dhcpcd  \
             -g dhcpcd           \
             -s /bin/false     \
             -u 52 dhcpcd
  fi
}
post_upgrade(){
  post_install
}

post_remove(){
  groupdel dhcpcd 2>/dev/null || true
  userdel dhcpcd 2>/dev/null  || true
}
