'\" t
.\"     Title: pkgdelta
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-02-23
.\"    Manual: Pacman Manual
.\"    Source: Pacman 5.0.1
.\"  Language: English
.\"
.TH "PKGDELTA" "8" "2016\-02\-23" "Pacman 5\&.0\&.1" "Pacman Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pkgdelta \- package delta generation utility
.SH "SYNOPSIS"
.sp
\fIpkgdelta\fR [options] <package1> <package2>
.SH "DESCRIPTION"
.sp
\fIpkgdelta\fR is used to create package delta files between two versions of the same package\&. These files are essentially binary patches\&. \fBpacman\fR(8) can download deltas instead of full package upgrades, and use them with the previous versions of packages (in the package cache) to synthesize the upgraded version of the packages\&. This likely reduces download sizes for upgrades significantly\&.
.sp
\fIpkgdelta\fR requires \fBxdelta3\fR(1) to do its job\&.
.SH "OPTIONS"
.PP
\fB\-\-max\-delta\-size <ratio>\fR
.RS 4
Only create delta files if the delta is smaller than ratio * package_size\&. Possible values: 0\&.0 to 2\&.0\&. Recommended values: 0\&.2 to 0\&.9\&. Default value: 0\&.7
.RE
.PP
\fB\-\-min\-pkg\-size <size>\fR
.RS 4
Minimal size of the package file in bytes to be considered for delta creation\&. Default value: 1048576 bytes = 1 MiB\&. This may be any absolute size in bytes or a human\-readable value such as
4MiB
or
3\&.5MB\&.
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Be quiet\&. Do not output anything but warnings and errors\&.
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ pkgdelta libreoffice\-3\&.3\&.2\-1\-x86_64\&.pkg\&.tar\&.xz libreoffice\-3\&.3\&.2\-2\-x86_64\&.pkg\&.tar\&.xz
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
\fBpacman\fR(8), \fBxdelta3\fR(1)
.sp
See the pacman website at https://www\&.archlinux\&.org/pacman/ for current information on pacman and its related tools\&.
.SH "BUGS"
.sp
Bugs? You must be kidding; there are no bugs in this software\&. But if we happen to be wrong, send us an email with as much detail as possible to pacman\-dev@archlinux\&.org\&.
.SH "AUTHORS"
.sp
Current maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Allan McRae <allan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Andrew Gregory <andrew\&.gregory\&.8@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dan McGee <dan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dave Reisner <dreisner@archlinux\&.org>
.RE
.sp
Past major contributors:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Judd Vinet <jvinet@zeroflux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aurelien Foret <aurelien@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aaron Griffin <aaron@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Xavier Chantry <shiningxc@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Nagy Gabor <ngaba@bibl\&.u\-szeged\&.hu>
.RE
.sp
For additional contributors, use git shortlog \-s on the pacman\&.git repository\&.
